import type { Property, Category, Location } from '@/types';

/**
 * Demo catalogue for properties_classic preview (/preview/*) or when
 * NEXT_PUBLIC_DEMO_FALLBACK=true. Not used on production storefronts.
 */
export const FALLBACK_CATEGORIES: Category[] = [
  { id: 1, title: 'Country Manors', slug: 'country-manors' },
  { id: 2, title: 'Historic Chateaus', slug: 'historic-chateaus' },
  { id: 3, title: 'Colonial Estates', slug: 'colonial-estates' },
  { id: 4, title: 'Royal Castles', slug: 'royal-castles' },
];

export const FALLBACK_LOCATIONS: Location[] = [
  { id: 1, title: 'Hertfordshire', country: 'UK', slug: 'hertfordshire' },
  { id: 2, title: 'Florence', country: 'Italy', slug: 'florence' },
  { id: 3, title: 'Loire Valley', country: 'France', slug: 'loire' },
];

export const FALLBACK_ESTATES: Property[] = [
  { id: 1, user_id: 1, category_id: 1, type_id: 1, location_id: 1, title: "The Pemberley Manor", slug: "pemberley-manor", description: "A majestic historic manor situated in the heart of Hertfordshire, featuring sweeping countryside views and rich architectural history.", base_price: 14200000, number_of_bedrooms: 6, number_of_bathrooms: 5, maximum_guests: 10, minimum_rental_days: 7, maximum_rental_days: 30, area_sq_ft: 12000, area_sq_m: 1114, number_of_parking_spots: 4, hoa: 200, year_built: 1815, address: "Pemberley Park", city: "Hertfordshire", state: "Herts", country: "UK", zip_code: "AL1 1AB", status: "active", is_published: true, is_featured: true, is_rental: false, is_sale: true, created_at: "", updated_at: "", pricing: { base_price: 14200000, price_formatted: "$14,200,000", currency_symbol: "$" }, location: { id: 1, title: "Hertfordshire", country: "UK", slug: "hertfordshire" }, specs: { bedrooms: 6, bathrooms: 5, area_formatted: "12,000 Sq Ft", year_built: 1815, category: "Country Manors", property_type: "Sale" }, featured_image: "/themes/properties/classic/1.webp", short_description: "A majestic historic manor situated in the heart of Hertfordshire, featuring sweeping countryside views and rich architectural history." },
  { id: 2, user_id: 1, category_id: 2, type_id: 1, location_id: 2, title: "Florentine Palazzo", slug: "florentine-palazzo", description: "An authentic Renaissance palace in central Florence, with original frescoes, grand vaulted halls, and private courtyard gardens.", base_price: 22500000, number_of_bedrooms: 8, number_of_bathrooms: 7, maximum_guests: 16, minimum_rental_days: 3, maximum_rental_days: 14, area_sq_ft: 18500, area_sq_m: 1718, number_of_parking_spots: 2, hoa: 500, year_built: 1540, address: "Via dei Bardi", city: "Florence", state: "Tuscany", country: "Italy", zip_code: "50125", status: "active", is_published: true, is_featured: false, is_rental: false, is_sale: true, created_at: "", updated_at: "", pricing: { base_price: 22500000, price_formatted: "$22,500,000", currency_symbol: "$" }, location: { id: 2, title: "Florence", country: "Italy", slug: "florence" }, specs: { bedrooms: 8, bathrooms: 7, area_formatted: "18,500 Sq Ft", year_built: 1540, category: "Historic Chateaus", property_type: "Sale" }, featured_image: "/themes/properties/classic/2.webp", short_description: "An authentic Renaissance palace in central Florence, with original frescoes, grand vaulted halls, and private courtyard gardens." },
  { id: 3, user_id: 1, category_id: 3, type_id: 1, location_id: 3, title: "Colonial River Estate", slug: "colonial-river-estate", description: "A meticulously preserved classic colonial estate on the banks of the James River, boasting rich heritage and timeless charm.", base_price: 8900000, number_of_bedrooms: 5, number_of_bathrooms: 4, maximum_guests: 8, minimum_rental_days: 1, maximum_rental_days: 365, area_sq_ft: 8200, area_sq_m: 761, number_of_parking_spots: 3, hoa: 100, year_built: 1742, address: "River Road", city: "Virginia", state: "VA", country: "USA", zip_code: "23220", status: "active", is_published: true, is_featured: false, is_rental: false, is_sale: true, created_at: "", updated_at: "", pricing: { base_price: 8900000, price_formatted: "$8,900,000", currency_symbol: "$" }, location: { id: 3, title: "Virginia", country: "USA", slug: "virginia" }, specs: { bedrooms: 5, bathrooms: 4, area_formatted: "8,200 Sq Ft", year_built: 1742, category: "Colonial Estates", property_type: "Sale" }, featured_image: "/themes/properties/classic/3.webp", short_description: "A meticulously preserved classic colonial estate on the banks of the James River, boasting rich heritage and timeless charm." },
  { id: 4, user_id: 1, category_id: 2, type_id: 1, location_id: 3, title: "Loire Valley Chateau", slug: "loire-valley-chateau", description: "A breathtaking French chateau with spectacular turrets, exquisite manicured formal gardens, and extensive woodland acreage.", base_price: 35000000, number_of_bedrooms: 12, number_of_bathrooms: 10, maximum_guests: 20, minimum_rental_days: 5, maximum_rental_days: 30, area_sq_ft: 24000, area_sq_m: 2229, number_of_parking_spots: 10, hoa: 800, year_built: 1620, address: "Chateau Road", city: "Loire", state: "Centre-Val de Loire", country: "France", zip_code: "37000", status: "active", is_published: true, is_featured: true, is_rental: false, is_sale: true, created_at: "", updated_at: "", pricing: { base_price: 35000000, price_formatted: "$35,000,000", currency_symbol: "$" }, location: { id: 3, title: "Loire Valley", country: "France", slug: "loire" }, specs: { bedrooms: 12, bathrooms: 10, area_formatted: "24,000 Sq Ft", year_built: 1620, category: "Historic Chateaus", property_type: "Sale" }, featured_image: "/themes/properties/classic/4.webp", short_description: "A breathtaking French chateau with spectacular turrets, exquisite manicured formal gardens, and extensive woodland acreage." },
  { id: 5, user_id: 1, category_id: 4, type_id: 1, location_id: 1, title: "Scottish Highland Castle", slug: "scottish-highland-castle", description: "A historic stone fortress overlooking the Scottish Highlands, complete with authentic battlements, grand hall, and private loch.", base_price: 12400000, number_of_bedrooms: 10, number_of_bathrooms: 8, maximum_guests: 18, minimum_rental_days: 2, maximum_rental_days: 14, area_sq_ft: 15000, area_sq_m: 1393, number_of_parking_spots: 6, hoa: 400, year_built: 1480, address: "Highland Way", city: "Inverness", state: "Highlands", country: "Scotland", zip_code: "IV1 1AA", status: "active", is_published: true, is_featured: false, is_rental: false, is_sale: true, created_at: "", updated_at: "", pricing: { base_price: 12400000, price_formatted: "$12,400,000", currency_symbol: "$" }, location: { id: 1, title: "Inverness", country: "Scotland", slug: "inverness" }, specs: { bedrooms: 10, bathrooms: 8, area_formatted: "15,000 Sq Ft", year_built: 1480, category: "Royal Castles", property_type: "Sale" }, featured_image: "/themes/properties/classic/5.webp", short_description: "A historic stone fortress overlooking the Scottish Highlands, complete with authentic battlements, grand hall, and private loch." },
  { id: 6, user_id: 1, category_id: 1, type_id: 1, location_id: 1, title: "Bavarian Hunting Lodge", slug: "bavarian-hunting-lodge", description: "An alpine timber lodge surrounded by deep Bavarian forests, offering ultimate privacy, heated floors, and a gorgeous stone hearth.", base_price: 6500000, number_of_bedrooms: 4, number_of_bathrooms: 3, maximum_guests: 6, minimum_rental_days: 3, maximum_rental_days: 30, area_sq_ft: 5800, area_sq_m: 538, number_of_parking_spots: 2, hoa: 150, year_built: 1895, address: "Alpine Lodge Weg", city: "Bavaria", state: "Bavaria", country: "Germany", zip_code: "80331", status: "active", is_published: true, is_featured: false, is_rental: false, is_sale: true, created_at: "", updated_at: "", pricing: { base_price: 6500000, price_formatted: "$6,500,000", currency_symbol: "$" }, location: { id: 1, title: "Bavaria", country: "Germany", slug: "bavaria" }, specs: { bedrooms: 4, bathrooms: 3, area_formatted: "5,800 Sq Ft", year_built: 1895, category: "Country Manors", property_type: "Sale" }, featured_image: "/themes/properties/classic/6.webp", short_description: "An alpine timber lodge surrounded by deep Bavarian forests, offering ultimate privacy, heated floors, and a gorgeous stone hearth." },
];

export const FALLBACK_ESTATE_IDS = new Set(FALLBACK_ESTATES.map((estate) => estate.id));

export const FALLBACK_CATALOG_ERROR =
  'Database returned no listings. Ensure seeders have run.';
