import type { Property, Category, Location } from '@/types';

const themeImage = (n: number) => `/themes/properties/rental/${n}.webp`;

export const FALLBACK_CATALOG_ERROR =
  'Rental catalog API returned no listings or could not be reached.';

export const FALLBACK_CATEGORIES: Category[] = [
  { id: 1, title: 'Studio', slug: 'studio' },
  { id: 2, title: 'Apartment', slug: 'apartment' },
  { id: 3, title: 'Loft', slug: 'loft' },
  { id: 4, title: 'Penthouse', slug: 'penthouse' },
  { id: 5, title: 'Townhouse', slug: 'townhouse' },
];

export const FALLBACK_LOCATIONS: Location[] = [
  { id: 1, title: 'Downtown Core', country: 'USA', slug: 'downtown-core' },
  { id: 2, title: 'West End District', country: 'USA', slug: 'west-end' },
  { id: 3, title: 'Financial Hub', country: 'USA', slug: 'financial-hub' },
];

export const FALLBACK_RENTALS: Property[] = [
  {
    id: 1,
    user_id: 1,
    category_id: 1,
    type_id: 1,
    location_id: 1,
    title: 'The North Tower Studio',
    slug: 'north-tower-studio',
    description:
      'Sleek studio in the heart of Downtown Core with skyline views and smart-home utilities.',
    short_description: 'Bright studio with skyline views and in-unit laundry.',
    base_price: 1850,
    number_of_bedrooms: 1,
    number_of_bathrooms: 1,
    maximum_guests: 2,
    minimum_rental_days: 30,
    maximum_rental_days: 365,
    area_sq_ft: 480,
    area_sq_m: 45,
    number_of_parking_spots: 1,
    hoa: 75,
    year_built: 2018,
    address: '100 Main Street',
    city: 'Downtown Core',
    state: 'NY',
    country: 'USA',
    zip_code: '10001',
    status: 'active',
    is_published: true,
    is_featured: false,
    is_rental: true,
    is_sale: false,
    created_at: '',
    updated_at: '',
    rules: null,
    policies: null,
    video: null,
    virtual_tour: null,
    pricing: { base_price: 1850, price_per_night: 1850, price_formatted: '$1,850' },
    location: { id: 1, title: 'Downtown Core', country: 'USA', slug: 'downtown-core' },
    specs: {
      bedrooms: 1,
      bathrooms: 1,
      area_formatted: '480 sq ft',
      category: 'Studio',
      property_type: 'Rent',
    },
    featured_image: themeImage(1),
    stock_count: 2,
  } as Property & { stock_count: number },
  {
    id: 2,
    user_id: 1,
    category_id: 2,
    type_id: 1,
    location_id: 2,
    title: 'Riverside 2BR Apartment',
    slug: 'riverside-2br-apartment',
    description: 'Dual-bedroom apartment along the river with oak flooring and transit access.',
    base_price: 2400,
    number_of_bedrooms: 2,
    number_of_bathrooms: 2,
    maximum_guests: 4,
    minimum_rental_days: 30,
    maximum_rental_days: 365,
    area_sq_ft: 950,
    area_sq_m: 88,
    number_of_parking_spots: 1,
    hoa: 85,
    year_built: 2019,
    address: '42 River Walk',
    city: 'West End District',
    state: 'NY',
    country: 'USA',
    zip_code: '10002',
    status: 'active',
    is_published: true,
    is_featured: false,
    is_rental: true,
    is_sale: false,
    created_at: '',
    updated_at: '',
    rules: null,
    policies: null,
    video: null,
    virtual_tour: null,
    pricing: { base_price: 2400, price_per_night: 2400, price_formatted: '$2,400' },
    location: { id: 2, title: 'West End District', country: 'USA', slug: 'west-end' },
    specs: {
      bedrooms: 2,
      bathrooms: 2,
      area_formatted: '950 sq ft',
      category: 'Apartment',
      property_type: 'Rent',
    },
    featured_image: themeImage(2),
  },
  {
    id: 3,
    user_id: 1,
    category_id: 3,
    type_id: 1,
    location_id: 2,
    title: 'Modern Industrial Loft',
    slug: 'modern-industrial-loft',
    description: 'Open-plan loft near galleries and dining in the Arts district.',
    base_price: 3100,
    number_of_bedrooms: 1,
    number_of_bathrooms: 1,
    maximum_guests: 3,
    minimum_rental_days: 30,
    maximum_rental_days: 365,
    area_sq_ft: 820,
    area_sq_m: 76,
    number_of_parking_spots: 1,
    hoa: 95,
    year_built: 2017,
    address: '8 Gallery Row',
    city: 'West End District',
    state: 'NY',
    country: 'USA',
    zip_code: '10003',
    status: 'active',
    is_published: true,
    is_featured: false,
    is_rental: true,
    is_sale: false,
    created_at: '',
    updated_at: '',
    rules: null,
    policies: null,
    video: null,
    virtual_tour: null,
    pricing: { base_price: 3100, price_per_night: 3100, price_formatted: '$3,100' },
    location: { id: 2, title: 'West End District', country: 'USA', slug: 'west-end' },
    specs: {
      bedrooms: 1,
      bathrooms: 1,
      area_formatted: '820 sq ft',
      category: 'Loft',
      property_type: 'Rent',
    },
    featured_image: themeImage(3),
    stock_count: 1,
  } as Property & { stock_count: number },
  {
    id: 4,
    user_id: 1,
    category_id: 4,
    type_id: 1,
    location_id: 3,
    title: 'Skyline Penthouse Unit',
    slug: 'skyline-penthouse-unit',
    description: 'Top-floor penthouse with private elevator and panoramic city views.',
    base_price: 5500,
    number_of_bedrooms: 3,
    number_of_bathrooms: 3,
    maximum_guests: 6,
    minimum_rental_days: 30,
    maximum_rental_days: 365,
    area_sq_ft: 1650,
    area_sq_m: 153,
    number_of_parking_spots: 2,
    hoa: 250,
    year_built: 2021,
    address: '1 Financial Plaza',
    city: 'Financial Hub District',
    state: 'NY',
    country: 'USA',
    zip_code: '10004',
    status: 'active',
    is_published: true,
    is_featured: true,
    is_rental: true,
    is_sale: false,
    created_at: '',
    updated_at: '',
    rules: null,
    policies: null,
    video: null,
    virtual_tour: null,
    pricing: { base_price: 5500, price_per_night: 5500, price_formatted: '$5,500' },
    location: { id: 3, title: 'Financial Hub', country: 'USA', slug: 'financial-hub' },
    specs: {
      bedrooms: 3,
      bathrooms: 3,
      area_formatted: '1,650 sq ft',
      category: 'Penthouse',
      property_type: 'Rent',
    },
    featured_image: themeImage(4),
    stock_count: 1,
  } as Property & { stock_count: number },
  {
    id: 5,
    user_id: 1,
    category_id: 5,
    type_id: 1,
    location_id: 1,
    title: 'Sunlit Family Townhouse',
    slug: 'sunlit-family-townhouse',
    description: 'Four-bedroom townhouse with garden and two-car garage.',
    base_price: 3800,
    number_of_bedrooms: 4,
    number_of_bathrooms: 3,
    maximum_guests: 8,
    minimum_rental_days: 30,
    maximum_rental_days: 365,
    area_sq_ft: 1900,
    area_sq_m: 177,
    number_of_parking_spots: 2,
    hoa: 120,
    year_built: 2016,
    address: '55 Pine Lane',
    city: 'Suburban Pines',
    state: 'NY',
    country: 'USA',
    zip_code: '10005',
    status: 'active',
    is_published: true,
    is_featured: false,
    is_rental: true,
    is_sale: false,
    created_at: '',
    updated_at: '',
    rules: null,
    policies: null,
    video: null,
    virtual_tour: null,
    pricing: { base_price: 3800, price_per_night: 3800, price_formatted: '$3,800' },
    location: { id: 1, title: 'Downtown Core', country: 'USA', slug: 'downtown-core' },
    specs: {
      bedrooms: 4,
      bathrooms: 3,
      area_formatted: '1,900 sq ft',
      category: 'Townhouse',
      property_type: 'Rent',
    },
    featured_image: themeImage(5),
    stock_count: 2,
  } as Property & { stock_count: number },
  {
    id: 6,
    user_id: 1,
    category_id: 1,
    type_id: 1,
    location_id: 1,
    title: 'Compact Downtown Micro-Studio',
    slug: 'compact-downtown-micro-studio',
    description: 'Efficient micro-studio optimized for single tenants near transit.',
    base_price: 1400,
    number_of_bedrooms: 1,
    number_of_bathrooms: 1,
    maximum_guests: 1,
    minimum_rental_days: 30,
    maximum_rental_days: 365,
    area_sq_ft: 350,
    area_sq_m: 33,
    number_of_parking_spots: 0,
    hoa: 50,
    year_built: 2020,
    address: '12 Loop Street',
    city: 'South Side Loop',
    state: 'NY',
    country: 'USA',
    zip_code: '10006',
    status: 'active',
    is_published: true,
    is_featured: false,
    is_rental: true,
    is_sale: false,
    created_at: '',
    updated_at: '',
    rules: null,
    policies: null,
    video: null,
    virtual_tour: null,
    pricing: { base_price: 1400, price_per_night: 1400, price_formatted: '$1,400' },
    location: { id: 1, title: 'Downtown Core', country: 'USA', slug: 'downtown-core' },
    specs: {
      bedrooms: 1,
      bathrooms: 1,
      area_formatted: '350 sq ft',
      category: 'Studio',
      property_type: 'Rent',
    },
    featured_image: themeImage(6),
  },
];
