import type { VacationRetreatCard } from './vacation-utils';

const PLACEHOLDER =
  "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='720' height='900' viewBox='0 0 720 900'><rect width='100%' height='100%' fill='%23f0f7ff'/><text x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' font-family='Inter,sans-serif' font-size='14' font-weight='700' fill='%2364748b'>RETREAT PHOTO</text></svg>";

export const FALLBACK_RETREATS: VacationRetreatCard[] = [
  {
    id: 1,
    title: 'Cliffside Aegean Villa',
    location: 'Santorini, Greece',
    price: '$1,200',
    numericPrice: 1200,
    rating: '4.97',
    image: PLACEHOLDER,
    slug: 'cliffside-aegean-villa',
    category: 'Villa',
    sqft: '3,800 sq ft',
    guests: '8 Guests',
    bedrooms: '4 Bedrooms',
    bathrooms: '4 Bathrooms',
    yearBuilt: 2019,
    vibeScore: '97/100',
    description:
      'Perched above the caldera with uninterrupted sunset views, this whitewashed villa features a heated infinity pool, private chef kitchen, and curated local art throughout.',
  },
  {
    id: 2,
    title: 'Rainforest Treehouse Estate',
    location: 'Monteverde, Costa Rica',
    price: '$480',
    numericPrice: 480,
    rating: '4.93',
    image: PLACEHOLDER,
    slug: 'rainforest-treehouse-estate',
    category: 'Treehouse',
    sqft: '1,200 sq ft',
    guests: '4 Guests',
    bedrooms: '2 Bedrooms',
    bathrooms: '2 Bathrooms',
    yearBuilt: 2021,
    vibeScore: '94/100',
    description:
      'Suspended among cloud-forest canopy at 1,600 metres, this architect-designed treehouse blends seamlessly with its surroundings via floor-to-ceiling glass walls and a wraparound deck.',
  },
  {
    id: 3,
    title: 'Overwater Bungalow — North Atoll',
    location: 'Baa Atoll, Maldives',
    price: '$2,100',
    numericPrice: 2100,
    rating: '5.00',
    image: PLACEHOLDER,
    slug: 'overwater-bungalow-north-atoll',
    category: 'Overwater',
    sqft: '2,100 sq ft',
    guests: '2 Guests',
    bedrooms: '1 Bedroom',
    bathrooms: '2 Bathrooms',
    yearBuilt: 2020,
    vibeScore: '99/100',
    description:
      'Direct lagoon access via your private ladder, a glass-panel floor for reef viewing, and a sunrise deck with butler-service breakfast. The definitive tropical escape.',
  },
  {
    id: 4,
    title: 'Alpine Chalet — Verbier Ridge',
    location: 'Verbier, Switzerland',
    price: '$3,400',
    numericPrice: 3400,
    rating: '4.98',
    image: PLACEHOLDER,
    slug: 'alpine-chalet-verbier-ridge',
    category: 'Chalet',
    sqft: '5,600 sq ft',
    guests: '12 Guests',
    bedrooms: '6 Bedrooms',
    bathrooms: '6 Bathrooms',
    yearBuilt: 2017,
    vibeScore: '98/100',
    description:
      'Ski-in/ski-out access to the Four Valleys, a private spa suite, wine cellar stocked with 300 bottles, and panoramic Mont Blanc views from the great-room fireplace.',
  },
  {
    id: 5,
    title: 'Desert Glass House',
    location: 'Joshua Tree, California, USA',
    price: '$650',
    numericPrice: 650,
    rating: '4.89',
    image: PLACEHOLDER,
    slug: 'desert-glass-house',
    category: 'Desert',
    sqft: '2,400 sq ft',
    guests: '6 Guests',
    bedrooms: '3 Bedrooms',
    bathrooms: '3 Bathrooms',
    yearBuilt: 2022,
    vibeScore: '91/100',
    description:
      'A minimalist modernist house with walls of glass opening to the Mojave. Stargazing deck, outdoor soaking tub, and a curated vinyl record collection for long evenings.',
  },
  {
    id: 6,
    title: 'Amalfi Coastal Palazzo',
    location: 'Positano, Italy',
    price: '$1,800',
    numericPrice: 1800,
    rating: '4.95',
    image: PLACEHOLDER,
    slug: 'amalfi-coastal-palazzo',
    category: 'Palazzo',
    sqft: '4,200 sq ft',
    guests: '10 Guests',
    bedrooms: '5 Bedrooms',
    bathrooms: '5 Bathrooms',
    yearBuilt: 1890,
    vibeScore: '96/100',
    description:
      'A restored 19th-century palazzo carved into the cliffside, with frescoed ceilings, a sea-terrace lemon grove, and a private boat mooring for day trips along the coast.',
  },
];
