import type { Vehicle } from '@sellio/types';

const publishedStatus = {
  is_published: true,
  is_featured: true,
  is_new_arrival: true,
};

const emptyTaxonomy = {
  category: null,
  brand: null,
  features: [],
  tags: [],
};

export const MODERN_FALLBACK_VEHICLES: Vehicle[] = [
  {
    id: 201,
    title: '2025 Tesla Model 3',
    slug: 'tesla-model-3',
    description:
      'The absolute standard in modern electric commuting with dual-motor AWD and industry-leading driver assist.',
    short_description: 'Futuristic all-electric dual-motor sedan with full autonomy suites.',
    pricing: {
      base_price: 39000,
      formatted: '$39,000',
      is_lease: true,
      is_selling: true,
    },
    specs: {
      year: 2025,
      make: 'Tesla',
      model: 'Model 3',
      condition: 'New',
      mileage: 'Available Now',
      engine: 'Electric Dual Motor',
      transmission: 'Automatic',
      drivetrain: 'AWD',
    },
    media: { main_photo: '/themes/autos/modern/11.webp' },
    taxonomy: emptyTaxonomy,
    location: { city: 'Palo Alto', state: 'CA', country: 'USA' },
    status: publishedStatus,
  },
  {
    id: 202,
    title: '2025 BMW i4',
    slug: 'bmw-i4',
    description: 'Gran Coupe styling meets advanced electric mobility and a curved display cockpit.',
    short_description: 'All-electric premium Gran Coupe showcasing athletic performance.',
    pricing: {
      base_price: 55000,
      formatted: '$55,000',
      is_lease: true,
      is_selling: true,
    },
    specs: {
      year: 2025,
      make: 'BMW',
      model: 'i4',
      condition: 'New',
      mileage: '800 mi',
      engine: 'eDrive40 Electric',
      transmission: 'Automatic',
      drivetrain: 'RWD',
    },
    media: { main_photo: '/themes/autos/modern/12.webp' },
    taxonomy: emptyTaxonomy,
    location: { city: 'Munich', state: 'Bavaria', country: 'Germany' },
    status: publishedStatus,
  },
  {
    id: 203,
    title: '2025 Toyota Corolla',
    slug: 'toyota-corolla',
    description: 'Reliable everyday vehicle upgraded with Toyota Safety Sense 3.0.',
    short_description: 'Unmatched daily reliability meets smart hybrid efficiency.',
    pricing: {
      base_price: 22000,
      formatted: '$22,000',
      is_lease: false,
      is_selling: true,
    },
    specs: {
      year: 2025,
      make: 'Toyota',
      model: 'Corolla',
      condition: 'New',
      mileage: '50 mi',
      engine: '2.0L 4-Cylinder Hybrid',
      transmission: 'CVT',
      drivetrain: 'FWD',
    },
    media: { main_photo: '/themes/autos/modern/13.webp' },
    taxonomy: emptyTaxonomy,
    location: { city: 'Toyota', state: 'Aichi', country: 'Japan' },
    status: publishedStatus,
  },
  {
    id: 204,
    title: '2025 Audi e-tron GT',
    slug: 'audi-e-tron-gt',
    description: 'A blistering electric masterpiece with quattro handling and hyper-charging options.',
    short_description: 'Aerodynamic dual-motor luxury tourer with hyper-charging options.',
    pricing: {
      base_price: 88000,
      formatted: '$88,000',
      is_lease: true,
      is_selling: true,
    },
    specs: {
      year: 2025,
      make: 'Audi',
      model: 'e-tron GT',
      condition: 'New',
      mileage: '150 mi',
      engine: 'Dual Motor e-quattro',
      transmission: '2-Speed Automatic',
      drivetrain: 'AWD',
    },
    media: { main_photo: '/themes/autos/modern/14.webp' },
    taxonomy: emptyTaxonomy,
    location: { city: 'Ingolstadt', state: 'Bavaria', country: 'Germany' },
    status: publishedStatus,
  },
  {
    id: 205,
    title: '2025 Hyundai IONIQ 6',
    slug: 'hyundai-ioniq-6',
    description: 'Ultra-aerodynamic EV streamliner with 800V charging compatibility.',
    short_description: 'Ultra-aerodynamic EV streamliner with 800V charging capabilities.',
    pricing: {
      base_price: 46000,
      formatted: '$46,000',
      is_lease: true,
      is_selling: true,
    },
    specs: {
      year: 2025,
      make: 'Hyundai',
      model: 'IONIQ 6',
      condition: 'New',
      mileage: '300 mi',
      engine: 'Electric Propulsion',
      transmission: 'Automatic',
      drivetrain: 'RWD',
    },
    media: { main_photo: '/themes/autos/modern/15.webp' },
    taxonomy: emptyTaxonomy,
    location: { city: 'Seoul', state: 'Seoul', country: 'South Korea' },
    status: publishedStatus,
  },
];

export const LUXURY_FALLBACK_VEHICLES: Vehicle[] = [
  {
    id: 101,
    title: '2025 Mercedes S-Class',
    slug: 'mercedes-s-class',
    description:
      'A pinnacle of luxury motoring with ambient multi-contour seating and unmatched road comfort.',
    short_description: 'Mild-hybrid luxury sedan with state-of-the-art cabin diagnostics.',
    pricing: {
      base_price: 110000,
      formatted: '$110,000',
      is_lease: true,
      is_selling: true,
    },
    specs: {
      year: 2025,
      make: 'Mercedes-Benz',
      model: 'S-Class',
      condition: '9.9/10',
      mileage: '5,000 mi',
      engine: 'Gasoline (Mild Hybrid)',
      transmission: 'Automatic',
      drivetrain: 'AWD',
      exterior_color: 'Obsidian Black',
      warranty: '48 Months',
    },
    media: { main_photo: '/themes/autos/luxury/mercedes.png' },
    taxonomy: emptyTaxonomy,
    location: { city: 'Los Angeles', state: 'CA', country: 'USA' },
    status: publishedStatus,
  },
  {
    id: 102,
    title: '2024 Rolls Royce Phantom',
    slug: 'rolls-royce-phantom',
    description: 'The absolute benchmark of automotive status with bespoke starlight headlining.',
    short_description: 'Hand-crafted V12 masterpiece representing ultimate status.',
    pricing: {
      base_price: 420000,
      formatted: '$420,000',
      is_lease: false,
      is_selling: true,
    },
    specs: {
      year: 2024,
      make: 'Rolls Royce',
      model: 'Phantom',
      condition: '10/10',
      mileage: '2,100 mi',
      engine: '6.75L V12 Twin-Turbo',
      transmission: 'Automatic',
      drivetrain: 'RWD',
      exterior_color: 'Selenite Grey',
      warranty: '72 Months',
    },
    media: { main_photo: '/themes/autos/luxury/rolls.png' },
    taxonomy: emptyTaxonomy,
    location: { city: 'Miami', state: 'FL', country: 'USA' },
    status: publishedStatus,
  },
  {
    id: 103,
    title: '2025 Porsche Taycan Turbo',
    slug: 'porsche-taycan',
    description: 'A blistering electric sports saloon with rapid charging and precise cornering.',
    short_description: 'All-electric performance coupe with lightning-fast charging.',
    pricing: {
      base_price: 160000,
      formatted: '$160,000',
      is_lease: true,
      is_selling: true,
    },
    specs: {
      year: 2025,
      make: 'Porsche',
      model: 'Taycan Turbo',
      condition: '9.8/10',
      mileage: '800 mi',
      engine: 'Electric Dual Motor',
      transmission: 'Automatic',
      drivetrain: 'AWD',
      exterior_color: 'Chalk White',
      warranty: '36 Months',
    },
    media: { main_photo: '/themes/autos/luxury/porsche.png' },
    taxonomy: emptyTaxonomy,
    location: { city: 'Austin', state: 'TX', country: 'USA' },
    status: publishedStatus,
  },
  {
    id: 104,
    title: '2023 Bentley Continental GT',
    slug: 'bentley-continental',
    description: 'Grand touring defined with raw sportiness and classic British craftsmanship.',
    short_description: 'Exquisite grand tourer combining speed and craftsmanship.',
    pricing: {
      base_price: 245000,
      formatted: '$245,000',
      is_lease: true,
      is_selling: true,
    },
    specs: {
      year: 2023,
      make: 'Bentley',
      model: 'Continental GT',
      condition: '9.6/10',
      mileage: '6,500 mi',
      engine: '4.0L V8 Twin-Turbo',
      transmission: 'Automatic',
      drivetrain: 'AWD',
      exterior_color: 'Tanzanite Blue',
      warranty: '36 Months',
    },
    media: { main_photo: '/themes/autos/luxury/bentley.png' },
    taxonomy: emptyTaxonomy,
    location: { city: 'Greenwich', state: 'CT', country: 'USA' },
    status: publishedStatus,
  },
];

export function findModernFallbackVehicle(slug: string): Vehicle | null {
  return MODERN_FALLBACK_VEHICLES.find((vehicle) => vehicle.slug === slug) || null;
}

export function findLuxuryFallbackVehicle(slug: string): Vehicle | null {
  return LUXURY_FALLBACK_VEHICLES.find((vehicle) => vehicle.slug === slug) || null;
}
