import { NextRequest, NextResponse } from 'next/server';

/**
 * Handles /preview/[themeKey]/[[...path]] requests generated by the admin panel.
 * Rewrites the URL to the real page path and sets the `theme` cookie so that
 * getActiveTheme() picks up the correct theme for the request.
 */
export function middleware(request: NextRequest) {
  const { pathname } = request.nextUrl;

  const match = pathname.match(/^\/preview\/([^/]+)(\/.*)?$/);
  if (!match) return NextResponse.next();

  const themeKey = match[1];
  const subPath = match[2] || '/';

  const rewriteUrl = request.nextUrl.clone();
  rewriteUrl.pathname = subPath;

  const response = NextResponse.rewrite(rewriteUrl);
  response.cookies.set('theme', themeKey, {
    path: '/',
    httpOnly: false,
    maxAge: 60 * 60 * 24 * 7,
    sameSite: 'lax',
  });

  return response;
}

export const config = {
  matcher: ['/preview/:path*'],
};
