import type { Property, Category, Location } from '@sellio/types';

const demoImage = (n: number) => `/demo-assets/properties/item-${String(n).padStart(2, '0')}.svg`;

/**
 * Demo catalogue for properties_modern preview (/preview/*) or when
 * NEXT_PUBLIC_DEMO_FALLBACK=true. Not used on production storefronts.
 */
export const FALLBACK_CATEGORIES: Category[] = [
  { id: 1, title: 'High-Rise Towers', slug: 'high-rise' },
  { id: 2, title: 'Mixed-Use Blocks', slug: 'mixed-use' },
  { id: 3, title: 'Waterfront Lofts', slug: 'waterfront' },
  { id: 4, title: 'Transit Hubs', slug: 'transit' },
];

export const FALLBACK_LOCATIONS: Location[] = [
  { id: 1, title: 'Manhattan', country: 'USA', slug: 'manhattan' },
  { id: 2, title: 'Shibuya', country: 'Japan', slug: 'shibuya' },
  { id: 3, title: 'Canary Wharf', country: 'UK', slug: 'canary-wharf' },
];

export const FALLBACK_ESTATES: Property[] = [
  {
    id: 1,
    user_id: 1,
    category_id: 1,
    type_id: 1,
    location_id: 1,
    title: 'Skyline Glass Tower — Unit 42A',
    slug: 'skyline-glass-tower-42a',
    description:
      'Corner residence with floor-to-ceiling glazing, integrated smart climate, and direct elevator access to the rooftop observatory deck.',
    base_price: 4200000,
    number_of_bedrooms: 3,
    number_of_bathrooms: 3,
    maximum_guests: 6,
    minimum_rental_days: 1,
    maximum_rental_days: 365,
    area_sq_ft: 2400,
    area_sq_m: 223,
    number_of_parking_spots: 2,
    hoa: 1200,
    year_built: 2022,
    address: '425 Park Avenue South',
    city: 'New York',
    state: 'NY',
    country: 'USA',
    zip_code: '10016',
    status: 'active',
    is_published: true,
    is_featured: true,
    is_rental: false,
    is_sale: true,
    created_at: '',
    updated_at: '',
    pricing: { base_price: 4200000, price_formatted: '$4,200,000', currency_symbol: '$' },
    location: { id: 1, title: 'Manhattan', country: 'USA', slug: 'manhattan' },
    specs: {
      bedrooms: 3,
      bathrooms: 3,
      area_formatted: '2,400 Sq Ft',
      year_built: 2022,
      category: 'High-Rise Towers',
      property_type: 'Sale',
      total_units: 1,
    },
    featured_image: demoImage(1),
    short_description: 'Corner glass residence with skyline observatory access.',
  },
  {
    id: 2,
    user_id: 1,
    category_id: 2,
    type_id: 1,
    location_id: 2,
    title: 'Shibuya Cross Block — Level 18',
    slug: 'shibuya-cross-block-18',
    description:
      'Mixed-use podium asset with retail at grade, co-working mezzanine, and residential loft above the transit concourse.',
    base_price: 3100000,
    number_of_bedrooms: 2,
    number_of_bathrooms: 2,
    maximum_guests: 4,
    minimum_rental_days: 1,
    maximum_rental_days: 365,
    area_sq_ft: 1850,
    area_sq_m: 172,
    number_of_parking_spots: 1,
    hoa: 800,
    year_built: 2020,
    address: '2-24-12 Shibuya',
    city: 'Tokyo',
    state: 'Tokyo',
    country: 'Japan',
    zip_code: '150-0002',
    status: 'active',
    is_published: true,
    is_featured: false,
    is_rental: false,
    is_sale: true,
    created_at: '',
    updated_at: '',
    pricing: { base_price: 3100000, price_formatted: '$3,100,000', currency_symbol: '$' },
    location: { id: 2, title: 'Shibuya', country: 'Japan', slug: 'shibuya' },
    specs: {
      bedrooms: 2,
      bathrooms: 2,
      area_formatted: '1,850 Sq Ft',
      year_built: 2020,
      category: 'Mixed-Use Blocks',
      property_type: 'Sale',
      total_units: 4,
    },
    featured_image: demoImage(2),
    short_description: 'Transit-linked mixed-use loft with co-working mezzanine.',
  },
  {
    id: 3,
    user_id: 1,
    category_id: 3,
    type_id: 1,
    location_id: 3,
    title: 'Thames Waterfront Loft',
    slug: 'thames-waterfront-loft',
    description:
      'Industrial conversion with exposed steel, river-facing terrace, and underfloor heating throughout the open-plan volume.',
    base_price: 2750000,
    number_of_bedrooms: 2,
    number_of_bathrooms: 2,
    maximum_guests: 4,
    minimum_rental_days: 1,
    maximum_rental_days: 365,
    area_sq_ft: 1650,
    area_sq_m: 153,
    number_of_parking_spots: 1,
    hoa: 450,
    year_built: 2018,
    address: '12 Harbour Exchange',
    city: 'London',
    state: 'England',
    country: 'UK',
    zip_code: 'E14 9GE',
    status: 'active',
    is_published: true,
    is_featured: false,
    is_rental: false,
    is_sale: true,
    created_at: '',
    updated_at: '',
    pricing: { base_price: 2750000, price_formatted: '$2,750,000', currency_symbol: '$' },
    location: { id: 3, title: 'Canary Wharf', country: 'UK', slug: 'canary-wharf' },
    specs: {
      bedrooms: 2,
      bathrooms: 2,
      area_formatted: '1,650 Sq Ft',
      year_built: 2018,
      category: 'Waterfront Lofts',
      property_type: 'Sale',
      total_units: 1,
    },
    featured_image: demoImage(3),
    short_description: 'River terrace loft in a precision-engineered conversion.',
  },
  {
    id: 4,
    user_id: 1,
    category_id: 1,
    type_id: 1,
    location_id: 1,
    title: 'Midtown Brutalist Stack — Penthouse',
    slug: 'midtown-brutalist-penthouse',
    description:
      'Double-height penthouse with cantilevered terrace, private elevator bank, and panoramic views across the financial district.',
    base_price: 8900000,
    number_of_bedrooms: 4,
    number_of_bathrooms: 4,
    maximum_guests: 8,
    minimum_rental_days: 1,
    maximum_rental_days: 365,
    area_sq_ft: 4200,
    area_sq_m: 390,
    number_of_parking_spots: 3,
    hoa: 2200,
    year_built: 2019,
    address: '200 Park Avenue',
    city: 'New York',
    state: 'NY',
    country: 'USA',
    zip_code: '10166',
    status: 'active',
    is_published: true,
    is_featured: true,
    is_rental: false,
    is_sale: true,
    created_at: '',
    updated_at: '',
    pricing: { base_price: 8900000, price_formatted: '$8,900,000', currency_symbol: '$' },
    location: { id: 1, title: 'Manhattan', country: 'USA', slug: 'manhattan' },
    specs: {
      bedrooms: 4,
      bathrooms: 4,
      area_formatted: '4,200 Sq Ft',
      year_built: 2019,
      category: 'High-Rise Towers',
      property_type: 'Sale',
      total_units: 1,
    },
    featured_image: demoImage(4),
    short_description: 'Cantilevered penthouse with private elevator and district views.',
  },
  {
    id: 5,
    user_id: 1,
    category_id: 4,
    type_id: 1,
    location_id: 2,
    title: 'Transit Hub Residences — Block C',
    slug: 'transit-hub-residences-c',
    description:
      'Compact urban units optimized for rail-adjacent living with acoustic glazing and shared amenity deck.',
    base_price: 1850000,
    number_of_bedrooms: 1,
    number_of_bathrooms: 1,
    maximum_guests: 2,
    minimum_rental_days: 1,
    maximum_rental_days: 365,
    area_sq_ft: 920,
    area_sq_m: 85,
    number_of_parking_spots: 0,
    hoa: 320,
    year_built: 2021,
    address: '1-1 Marunouchi',
    city: 'Tokyo',
    state: 'Tokyo',
    country: 'Japan',
    zip_code: '100-0005',
    status: 'active',
    is_published: true,
    is_featured: false,
    is_rental: true,
    is_sale: true,
    created_at: '',
    updated_at: '',
    pricing: { base_price: 1850000, price_formatted: '$1,850,000', currency_symbol: '$', price_per_night: 420 },
    location: { id: 2, title: 'Shibuya', country: 'Japan', slug: 'shibuya' },
    specs: {
      bedrooms: 1,
      bathrooms: 1,
      area_formatted: '920 Sq Ft',
      year_built: 2021,
      category: 'Transit Hubs',
      property_type: 'Rent',
      total_units: 12,
    },
    featured_image: demoImage(5),
    short_description: 'Rail-adjacent micro-residence with acoustic glazing package.',
  },
  {
    id: 6,
    user_id: 1,
    category_id: 2,
    type_id: 1,
    location_id: 3,
    title: 'Docklands Innovation Stack',
    slug: 'docklands-innovation-stack',
    description:
      'Lab-ready floor plates with 4.2m ceiling height, freight lift access, and fiber backbone for distributed teams.',
    base_price: 5400000,
    number_of_bedrooms: 0,
    number_of_bathrooms: 2,
    maximum_guests: 20,
    minimum_rental_days: 1,
    maximum_rental_days: 365,
    area_sq_ft: 6800,
    area_sq_m: 632,
    number_of_parking_spots: 6,
    hoa: 1500,
    year_built: 2023,
    address: '5 Canada Square',
    city: 'London',
    state: 'England',
    country: 'UK',
    zip_code: 'E14 5AQ',
    status: 'active',
    is_published: true,
    is_featured: false,
    is_rental: false,
    is_sale: true,
    created_at: '',
    updated_at: '',
    pricing: { base_price: 5400000, price_formatted: '$5,400,000', currency_symbol: '$' },
    location: { id: 3, title: 'Canary Wharf', country: 'UK', slug: 'canary-wharf' },
    specs: {
      bedrooms: 0,
      bathrooms: 2,
      area_formatted: '6,800 Sq Ft',
      year_built: 2023,
      category: 'Mixed-Use Blocks',
      property_type: 'Sale',
      total_units: 8,
    },
    featured_image: demoImage(6),
    short_description: 'High-clearance innovation floor with freight lift and fiber backbone.',
  },
];

export const FALLBACK_CATALOG_ERROR =
  'Database returned no listings. Ensure seeders have run.';
