import type { JobListing } from '@sellio/types';

const publishedStatus = {
  is_published: true,
  is_featured: true,
  is_expired: false,
};

function buildJob(
  id: number,
  title: string,
  slug: string,
  description: string,
  company: string,
  category: string,
  workplace: string,
  workplaceId: number,
  experience: string,
  locationDisplay: string,
  city: string,
  country: string,
  rangeCompact: string,
  rangeFull: string,
  min: number,
  max: number,
  tags: string[],
): JobListing {
  return {
    id,
    title,
    slug,
    description,
    employment: {
      type: 'Full-time',
      workplace,
      workplace_id: workplaceId,
      experience_level: experience,
      education: 'Relevant industry experience',
      is_full_time: true,
      is_contract: false,
    },
    compensation: {
      min,
      max,
      frequency: 'yearly',
      range_compact: rangeCompact,
      range_full: rangeFull,
    },
    company: { name: company, logo: null },
    taxonomy: { category, tags },
    location: { display: locationDisplay, city, country },
    status: publishedStatus,
  };
}

export const STARTUP_FALLBACK_JOBS: JobListing[] = [
  buildJob(
    991,
    'Founding Engineer (Rust)',
    'nexus-rust-engineer',
    'Nexus.AI is looking for an elite Founding Rust Engineer to architect high-throughput distributed system node pipelines.',
    'Nexus.AI',
    'Engineering',
    'Remote',
    1,
    'Senior / Principal',
    'San Francisco / Remote',
    'San Francisco',
    'United States',
    '$140k–$210k/yr',
    '$140,000 - $210,000/yr',
    140000,
    210000,
    ['Rust', 'Distributed Systems', 'WebAssembly', 'Series A'],
  ),
  buildJob(
    992,
    'Head of Protocol Growth',
    'head-of-protocol-growth',
    'Lead growth strategy for an early-stage protocol company expanding across European and APAC markets.',
    'Aether Labs',
    'Growth',
    'Hybrid',
    3,
    'Senior',
    'Berlin / Hybrid',
    'Berlin',
    'Germany',
    '$120k–$165k/yr',
    '$120,000 - $165,000/yr',
    120000,
    165000,
    ['Growth', 'Web3', 'Seed+'],
  ),
  buildJob(
    993,
    'Senior Solidity Architect',
    'senior-solidity-architect',
    'Design secure smart contract systems and mentor engineers building DeFi infrastructure at scale.',
    'Void Capital',
    'Engineering',
    'Remote',
    1,
    'Senior',
    'Singapore / Remote',
    'Singapore',
    'Singapore',
    '$160k–$220k/yr',
    '$160,000 - $220,000/yr',
    160000,
    220000,
    ['Solidity', 'DeFi', 'Series B'],
  ),
  buildJob(
    994,
    'Lead Product Designer',
    'lead-product-designer',
    'Own product design for a venture-backed orbital systems platform from discovery through launch.',
    'Orbital Systems',
    'Product Design',
    'On-Site',
    2,
    'Lead',
    'Austin / On-site',
    'Austin',
    'United States',
    '$130k–$175k/yr',
    '$130,000 - $175,000/yr',
    130000,
    175000,
    ['Product Design', 'Series A', 'B2B SaaS'],
  ),
  buildJob(
    995,
    'DevOps / Infrastructure',
    'devops-infrastructure',
    'Build resilient cloud infrastructure and CI/CD pipelines for a fast-scaling cyber security startup.',
    'Cyber Node',
    'Operations',
    'Remote',
    1,
    'Mid-level',
    'London / Remote',
    'London',
    'United Kingdom',
    '$95k–$140k/yr',
    '$95,000 - $140,000/yr',
    95000,
    140000,
    ['DevOps', 'Kubernetes', 'Seed'],
  ),
  buildJob(
    996,
    'Growth Marketing Lead',
    'growth-marketing-lead',
    'Drive acquisition and lifecycle campaigns for a hypergrowth protocol marketing team.',
    'Scale Protocol',
    'Marketing',
    'Hybrid',
    3,
    'Senior',
    'New York / Hybrid',
    'New York',
    'United States',
    '$110k–$150k/yr',
    '$110,000 - $150,000/yr',
    110000,
    150000,
    ['Growth Marketing', 'Series A', 'Analytics'],
  ),
];

export const CORPORATE_FALLBACK_JOBS: JobListing[] = [
  {
    ...buildJob(
      801,
      'Director of Enterprise Sales',
      'director-enterprise-sales',
      'Lead global enterprise sales strategy for a Fortune 500 technology partner with multi-region accountability.',
      'GlobalTech Partners',
      'Sales',
      'Hybrid',
      3,
      'Director',
      'Chicago, IL',
      'Chicago',
      'United States',
      '$180k–$240k/yr',
      '$180,000 - $240,000/yr',
      180000,
      240000,
      ['Enterprise', 'SaaS', 'Leadership'],
    ),
    company: {
      name: 'GlobalTech Partners',
      logo: null,
      logo_card: '/themes/jobs/corporate/1.webp',
    },
  },
  {
    ...buildJob(
      802,
      'Senior Financial Analyst',
      'senior-financial-analyst',
      'Support corporate FP&A planning, forecasting, and executive reporting for a public enterprise group.',
      'Meridian Holdings',
      'Finance',
      'On-Site',
      2,
      'Mid-Senior',
      'New York, NY',
      'New York',
      'United States',
      '$120k–$155k/yr',
      '$120,000 - $155,000/yr',
      120000,
      155000,
      ['FP&A', 'Excel', 'Corporate Finance'],
    ),
    company: {
      name: 'Meridian Holdings',
      logo: null,
      logo_card: '/themes/jobs/corporate/2.webp',
    },
  },
  {
    ...buildJob(
      803,
      'VP of Human Resources',
      'vp-human-resources',
      'Own people operations, talent strategy, and organizational design for a multinational employer brand.',
      'Summit Industries',
      'Human Resources',
      'Hybrid',
      3,
      'Executive',
      'Boston, MA',
      'Boston',
      'United States',
      '$210k–$280k/yr',
      '$210,000 - $280,000/yr',
      210000,
      280000,
      ['HR Leadership', 'Talent', 'Compliance'],
    ),
    company: {
      name: 'Summit Industries',
      logo: null,
      logo_card: '/themes/jobs/corporate/3.webp',
    },
  },
  {
    ...buildJob(
      804,
      'Corporate Legal Counsel',
      'corporate-legal-counsel',
      'Advise on commercial contracts, regulatory matters, and cross-border compliance for enterprise clients.',
      'Atlas Corporation',
      'Legal',
      'Remote',
      1,
      'Senior',
      'Remote',
      'Remote',
      'United States',
      '$165k–$210k/yr',
      '$165,000 - $210,000/yr',
      165000,
      210000,
      ['Legal', 'Contracts', 'Compliance'],
    ),
    company: {
      name: 'Atlas Corporation',
      logo: null,
      logo_card: '/themes/jobs/corporate/4.webp',
    },
  },
  {
    ...buildJob(
      805,
      'Product Marketing Manager',
      'product-marketing-manager',
      'Launch B2B product narratives, positioning, and sales enablement for an enterprise software portfolio.',
      'Northline Systems',
      'Marketing',
      'Hybrid',
      3,
      'Mid-Senior',
      'Seattle, WA',
      'Seattle',
      'United States',
      '$130k–$165k/yr',
      '$130,000 - $165,000/yr',
      130000,
      165000,
      ['Product Marketing', 'B2B', 'Go-to-Market'],
    ),
    company: {
      name: 'Northline Systems',
      logo: null,
      logo_card: '/themes/jobs/corporate/5.webp',
    },
  },
  {
    ...buildJob(
      806,
      'Senior Data Engineer',
      'senior-data-engineer',
      'Build enterprise data pipelines and analytics platforms supporting executive decision systems.',
      'Pinnacle Analytics',
      'Engineering',
      'Remote',
      1,
      'Senior',
      'Remote',
      'Remote',
      'United States',
      '$150k–$190k/yr',
      '$150,000 - $190,000/yr',
      150000,
      190000,
      ['Data Engineering', 'Snowflake', 'Python'],
    ),
    company: {
      name: 'Pinnacle Analytics',
      logo: null,
      logo_card: '/themes/jobs/corporate/1.webp',
    },
  },
];

export function findStartupFallbackJob(slug: string): JobListing | undefined {
  const exact = STARTUP_FALLBACK_JOBS.find((job) => job.slug === slug);
  if (exact) return exact;

  return {
    ...STARTUP_FALLBACK_JOBS[0],
    id: 999,
    title: slug.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase()),
    slug,
    description:
      'Hypergrowth startup looking for a mission-critical specialist to optimize dynamic corporate networks and implement foundational microservice systems.',
    company: { name: 'Venture Corp', logo: null },
    taxonomy: { category: 'Technical Talent', tags: ['Startup', 'Next.js', 'Docker', 'Seed'] },
    location: { display: 'Berlin / Remote', city: 'Berlin', country: 'Germany' },
  };
}

export function findCorporateFallbackJob(slug: string): JobListing | undefined {
  return CORPORATE_FALLBACK_JOBS.find((job) => job.slug === slug);
}

export function getStartupRelatedJobs(slug: string): JobListing[] {
  return STARTUP_FALLBACK_JOBS.filter((job) => job.slug !== slug).slice(0, 3);
}

export function getCorporateRelatedJobs(slug: string): JobListing[] {
  return CORPORATE_FALLBACK_JOBS.filter((job) => job.slug !== slug).slice(0, 3);
}
