import type { JobListing } from '@sellio/types';

const publishedStatus = {
  is_published: true,
  is_featured: true,
  is_expired: false,
};

function buildJob(
  id: number,
  title: string,
  slug: string,
  description: string,
  company: string,
  category: string,
  workplace: string,
  workplaceId: number,
  experience: string,
  locationDisplay: string,
  city: string,
  country: string,
  rangeCompact: string,
  rangeFull: string,
  min: number,
  max: number,
  tags: string[],
): JobListing {
  return {
    id,
    title,
    slug,
    description,
    employment: {
      type: 'Full-time',
      workplace,
      workplace_id: workplaceId,
      experience_level: experience,
      education: 'Relevant industry experience',
      is_full_time: true,
      is_contract: false,
    },
    compensation: {
      min,
      max,
      frequency: 'yearly',
      range_compact: rangeCompact,
      range_full: rangeFull,
    },
    company: { name: company, logo: null },
    taxonomy: { category, tags },
    location: { display: locationDisplay, city, country },
    status: publishedStatus,
  };
}

export const STARTUP_FALLBACK_JOBS: JobListing[] = [
  buildJob(
    991,
    'Founding Engineer (Rust)',
    'nexus-rust-engineer',
    'Nexus.AI is looking for an elite Founding Rust Engineer to architect high-throughput distributed system node pipelines.',
    'Nexus.AI',
    'Engineering',
    'Remote',
    1,
    'Senior / Principal',
    'San Francisco / Remote',
    'San Francisco',
    'United States',
    '$140k–$210k/yr',
    '$140,000 - $210,000/yr',
    140000,
    210000,
    ['Rust', 'Distributed Systems', 'WebAssembly', 'Series A'],
  ),
  buildJob(
    992,
    'Head of Protocol Growth',
    'head-of-protocol-growth',
    'Lead growth strategy for an early-stage protocol company expanding across European and APAC markets.',
    'Aether Labs',
    'Growth',
    'Hybrid',
    3,
    'Senior',
    'Berlin / Hybrid',
    'Berlin',
    'Germany',
    '$120k–$165k/yr',
    '$120,000 - $165,000/yr',
    120000,
    165000,
    ['Growth', 'Web3', 'Seed+'],
  ),
  buildJob(
    993,
    'Senior Solidity Architect',
    'senior-solidity-architect',
    'Design secure smart contract systems and mentor engineers building DeFi infrastructure at scale.',
    'Void Capital',
    'Engineering',
    'Remote',
    1,
    'Senior',
    'Singapore / Remote',
    'Singapore',
    'Singapore',
    '$160k–$220k/yr',
    '$160,000 - $220,000/yr',
    160000,
    220000,
    ['Solidity', 'DeFi', 'Series B'],
  ),
  buildJob(
    994,
    'Lead Product Designer',
    'lead-product-designer',
    'Own product design for a venture-backed orbital systems platform from discovery through launch.',
    'Orbital Systems',
    'Product Design',
    'On-Site',
    2,
    'Lead',
    'Austin / On-site',
    'Austin',
    'United States',
    '$130k–$175k/yr',
    '$130,000 - $175,000/yr',
    130000,
    175000,
    ['Product Design', 'Series A', 'B2B SaaS'],
  ),
  buildJob(
    995,
    'DevOps / Infrastructure',
    'devops-infrastructure',
    'Build resilient cloud infrastructure and CI/CD pipelines for a fast-scaling cyber security startup.',
    'Cyber Node',
    'Operations',
    'Remote',
    1,
    'Mid-level',
    'London / Remote',
    'London',
    'United Kingdom',
    '$95k–$140k/yr',
    '$95,000 - $140,000/yr',
    95000,
    140000,
    ['DevOps', 'Kubernetes', 'Seed'],
  ),
  buildJob(
    996,
    'Growth Marketing Lead',
    'growth-marketing-lead',
    'Drive acquisition and lifecycle campaigns for a hypergrowth protocol marketing team.',
    'Scale Protocol',
    'Marketing',
    'Hybrid',
    3,
    'Senior',
    'New York / Hybrid',
    'New York',
    'United States',
    '$110k–$150k/yr',
    '$110,000 - $150,000/yr',
    110000,
    150000,
    ['Growth Marketing', 'Series A', 'Analytics'],
  ),
];

export const CORPORATE_FALLBACK_JOBS: JobListing[] = [
  {
    ...buildJob(
      801,
      'Director of Enterprise Sales',
      'director-enterprise-sales',
      'Lead global enterprise sales strategy for a Fortune 500 technology partner with multi-region accountability.',
      'GlobalTech Partners',
      'Sales',
      'Hybrid',
      3,
      'Director',
      'Chicago, IL',
      'Chicago',
      'United States',
      '$180k–$240k/yr',
      '$180,000 - $240,000/yr',
      180000,
      240000,
      ['Enterprise', 'SaaS', 'Leadership'],
    ),
    company: {
      name: 'GlobalTech Partners',
      logo: null,
      logo_card: '/themes/jobs/corporate/1.webp',
    },
  },
  {
    ...buildJob(
      802,
      'Senior Financial Analyst',
      'senior-financial-analyst',
      'Support corporate FP&A planning, forecasting, and executive reporting for a public enterprise group.',
      'Meridian Holdings',
      'Finance',
      'On-Site',
      2,
      'Mid-Senior',
      'New York, NY',
      'New York',
      'United States',
      '$120k–$155k/yr',
      '$120,000 - $155,000/yr',
      120000,
      155000,
      ['FP&A', 'Excel', 'Corporate Finance'],
    ),
    company: {
      name: 'Meridian Holdings',
      logo: null,
      logo_card: '/themes/jobs/corporate/2.webp',
    },
  },
  {
    ...buildJob(
      803,
      'VP of Human Resources',
      'vp-human-resources',
      'Own people operations, talent strategy, and organizational design for a multinational employer brand.',
      'Summit Industries',
      'Human Resources',
      'Hybrid',
      3,
      'Executive',
      'Boston, MA',
      'Boston',
      'United States',
      '$210k–$280k/yr',
      '$210,000 - $280,000/yr',
      210000,
      280000,
      ['HR Leadership', 'Talent', 'Compliance'],
    ),
    company: {
      name: 'Summit Industries',
      logo: null,
      logo_card: '/themes/jobs/corporate/3.webp',
    },
  },
  {
    ...buildJob(
      804,
      'Corporate Legal Counsel',
      'corporate-legal-counsel',
      'Advise on commercial contracts, regulatory matters, and cross-border compliance for enterprise clients.',
      'Atlas Corporation',
      'Legal',
      'Remote',
      1,
      'Senior',
      'Remote',
      'Remote',
      'United States',
      '$165k–$210k/yr',
      '$165,000 - $210,000/yr',
      165000,
      210000,
      ['Legal', 'Contracts', 'Compliance'],
    ),
    company: {
      name: 'Atlas Corporation',
      logo: null,
      logo_card: '/themes/jobs/corporate/4.webp',
    },
  },
  {
    ...buildJob(
      805,
      'Product Marketing Manager',
      'product-marketing-manager',
      'Launch B2B product narratives, positioning, and sales enablement for an enterprise software portfolio.',
      'Northline Systems',
      'Marketing',
      'Hybrid',
      3,
      'Mid-Senior',
      'Seattle, WA',
      'Seattle',
      'United States',
      '$130k–$165k/yr',
      '$130,000 - $165,000/yr',
      130000,
      165000,
      ['Product Marketing', 'B2B', 'Go-to-Market'],
    ),
    company: {
      name: 'Northline Systems',
      logo: null,
      logo_card: '/themes/jobs/corporate/5.webp',
    },
  },
  {
    ...buildJob(
      806,
      'Senior Data Engineer',
      'senior-data-engineer',
      'Build enterprise data pipelines and analytics platforms supporting executive decision systems.',
      'Pinnacle Analytics',
      'Engineering',
      'Remote',
      1,
      'Senior',
      'Remote',
      'Remote',
      'United States',
      '$150k–$190k/yr',
      '$150,000 - $190,000/yr',
      150000,
      190000,
      ['Data Engineering', 'Snowflake', 'Python'],
    ),
    company: {
      name: 'Pinnacle Analytics',
      logo: null,
      logo_card: '/themes/jobs/corporate/1.webp',
    },
  },
];

export function findStartupFallbackJob(slug: string): JobListing | undefined {
  return findFallbackJob(slug, 'startup');
}

export function findCorporateFallbackJob(slug: string): JobListing | undefined {
  return findFallbackJob(slug, 'corporate');
}

export function getStartupRelatedJobs(slug: string): JobListing[] {
  return getRelatedFallbackJobs(slug, 'startup');
}

export function getCorporateRelatedJobs(slug: string): JobListing[] {
  return getRelatedFallbackJobs(slug, 'corporate');
}

export const TECH_FALLBACK_JOBS: JobListing[] = [
  buildJob(
    901,
    'Senior React Engineer',
    'senior-react-engineer',
    "Join the core framework team to innovate Next.js and frontend delivery systems. Optimize compilation streams, hydration metrics, and SSR edge rendering.",
    'Vercel',
    'Engineering',
    'Remote',
    1,
    'Senior',
    'Remote - Worldwide',
    'Remote',
    'United States',
    '$140k–$180k/yr',
    '$140,000 - $180,000/yr',
    140000,
    180000,
    ['React', 'Next.js', 'TypeScript'],
  ),
  buildJob(
    902,
    'Backend Systems Developer',
    'backend-systems-developer',
    'Architect robust transactional APIs and secure ledger databases that route global trade and multi-currency billing networks.',
    'Stripe',
    'Engineering',
    'Remote',
    1,
    'Senior',
    'Remote - US/Canada',
    'Remote',
    'United States',
    '$160k–$210k/yr',
    '$160,000 - $210,000/yr',
    160000,
    210000,
    ['Go', 'Ruby', 'PostgreSQL', 'AWS'],
  ),
  buildJob(
    903,
    'Frontend Architect',
    'frontend-architect',
    'Craft highly interactive, responsive tooling for task management workflows with keyboard-first navigation.',
    'Linear',
    'Engineering',
    'On-Site',
    2,
    'Senior',
    'San Francisco, CA',
    'San Francisco',
    'United States',
    '$180k–$220k/yr',
    '$180,000 - $220,000/yr',
    180000,
    220000,
    ['React', 'GraphQL', 'MobX'],
  ),
  buildJob(
    904,
    'DevOps Engineer',
    'devops-engineer',
    'Manage highly scalable orchestration nodes routing voice and socket data across multi-cloud clusters.',
    'Discord',
    'Operations',
    'Remote',
    1,
    'Mid-level',
    'Remote - US',
    'Remote',
    'United States',
    '$150k–$190k/yr',
    '$150,000 - $190,000/yr',
    150000,
    190000,
    ['Kubernetes', 'Rust', 'GCP'],
  ),
  buildJob(
    905,
    'Full Stack Developer',
    'full-stack-developer',
    'Develop and scale open-source database client abstractions and serverless edge functions.',
    'Supabase',
    'Engineering',
    'Remote',
    1,
    'Mid-level',
    'Remote - EMEA',
    'Remote',
    'United Kingdom',
    '$120k–$150k/yr',
    '$120,000 - $150,000/yr',
    120000,
    150000,
    ['TypeScript', 'PostgreSQL', 'Elixir'],
  ),
];

export const MODERN_FALLBACK_JOBS: JobListing[] = [
  buildJob(
    911,
    'Senior Product Designer',
    'senior-product-designer',
    'Own end-to-end product design for a fast-growing SaaS platform serving millions of users.',
    'Nova Labs',
    'Design',
    'Hybrid',
    3,
    'Senior',
    'New York, NY',
    'New York',
    'United States',
    '$130k–$165k/yr',
    '$130,000 - $165,000/yr',
    130000,
    165000,
    ['Figma', 'Design Systems', 'SaaS'],
  ),
  buildJob(
    912,
    'Growth Marketing Manager',
    'growth-marketing-manager',
    'Drive acquisition campaigns and lifecycle programs for an ambitious consumer fintech brand.',
    'PulsePay',
    'Marketing',
    'Remote',
    1,
    'Mid-level',
    'Remote',
    'Remote',
    'United States',
    '$95k–$130k/yr',
    '$95,000 - $130,000/yr',
    95000,
    130000,
    ['Growth', 'Paid Media', 'Analytics'],
  ),
  buildJob(
    913,
    'Staff Software Engineer',
    'staff-software-engineer',
    'Lead platform architecture decisions and mentor engineers building high-scale APIs.',
    'Cloudframe',
    'Engineering',
    'Hybrid',
    3,
    'Staff',
    'Seattle, WA',
    'Seattle',
    'United States',
    '$170k–$220k/yr',
    '$170,000 - $220,000/yr',
    170000,
    220000,
    ['TypeScript', 'AWS', 'Platform'],
  ),
  buildJob(
    914,
    'Customer Success Lead',
    'customer-success-lead',
    'Build onboarding playbooks and retention programs for enterprise SaaS accounts.',
    'Brightdesk',
    'Customer Success',
    'Remote',
    1,
    'Lead',
    'Remote - US',
    'Remote',
    'United States',
    '$110k–$145k/yr',
    '$110,000 - $145,000/yr',
    110000,
    145000,
    ['SaaS', 'Enterprise', 'Retention'],
  ),
];

export const FREELANCE_FALLBACK_JOBS: JobListing[] = [
  buildJob(
    921,
    'Brand Identity Designer',
    'brand-identity-designer',
    'Create premium logo systems, style guides, and launch assets for funded startups.',
    'Studio Meridian',
    'Design',
    'Remote',
    1,
    'Expert',
    'Remote',
    'Remote',
    'United States',
    '$800–$2,500/project',
    '$800 - $2,500/project',
    800,
    2500,
    ['Branding', 'Logo', 'Figma'],
  ),
  buildJob(
    922,
    'React Developer for MVP',
    'react-developer-mvp',
    'Build a polished MVP dashboard with authentication, billing, and admin tooling.',
    'Launch Collective',
    'Programming',
    'Remote',
    1,
    'Mid-level',
    'Remote',
    'Remote',
    'United States',
    '$60–$120/hr',
    '$60 - $120/hr',
    60,
    120,
    ['React', 'Next.js', 'Stripe'],
  ),
  buildJob(
    923,
    'SEO Content Strategist',
    'seo-content-strategist',
    'Plan and write high-converting landing pages and blog content for B2B SaaS brands.',
    'RankForge',
    'Writing',
    'Remote',
    1,
    'Senior',
    'Remote',
    'Remote',
    'United Kingdom',
    '$45–$85/hr',
    '$45 - $85/hr',
    45,
    85,
    ['SEO', 'Copywriting', 'SaaS'],
  ),
  buildJob(
    924,
    'Video Editor for Product Launch',
    'video-editor-product-launch',
    'Edit launch trailers, social cutdowns, and paid ad creatives for a consumer app release.',
    'Motion Hive',
    'Video',
    'Remote',
    1,
    'Mid-level',
    'Remote',
    'Remote',
    'Canada',
    '$500–$1,800/project',
    '$500 - $1,800/project',
    500,
    1800,
    ['Premiere', 'After Effects', 'Ads'],
  ),
];

export const BLUE_COLLAR_FALLBACK_JOBS: JobListing[] = [
  buildJob(
    931,
    'Licensed Electrician',
    'licensed-electrician',
    'Commercial wiring projects with union benefits, overtime availability, and tool stipend.',
    'Metro Power Co.',
    'Electrical',
    'On-Site',
    2,
    'Journeyman',
    'Chicago, IL',
    'Chicago',
    'United States',
    '$32–$42/hr',
    '$32 - $42/hr',
    32,
    42,
    ['Commercial', 'Union', 'Licensed'],
  ),
  buildJob(
    932,
    'CNC Machine Operator',
    'cnc-machine-operator',
    'Operate precision CNC equipment for aerospace components on second shift with training provided.',
    'Precision Works',
    'Manufacturing',
    'On-Site',
    2,
    'Mid-level',
    'Detroit, MI',
    'Detroit',
    'United States',
    '$22–$28/hr',
    '$22 - $28/hr',
    22,
    28,
    ['CNC', 'Manufacturing', 'Aerospace'],
  ),
  buildJob(
    933,
    'CDL Class A Driver',
    'cdl-class-a-driver',
    'Regional routes with home weekly schedule, sign-on bonus, and full benefits package.',
    'Heartland Logistics',
    'Transportation',
    'On-Site',
    2,
    'Experienced',
    'Dallas, TX',
    'Dallas',
    'United States',
    '$0.58–$0.72/mi',
    '$0.58 - $0.72/mi',
    58,
    72,
    ['CDL', 'Regional', 'Benefits'],
  ),
  buildJob(
    934,
    'Commercial HVAC Technician',
    'commercial-hvac-technician',
    'Service and install rooftop units for commercial clients with overtime and company vehicle.',
    'CoolAir Services',
    'Maintenance',
    'On-Site',
    2,
    'Mid-level',
    'Phoenix, AZ',
    'Phoenix',
    'United States',
    '$28–$36/hr',
    '$28 - $36/hr',
    28,
    36,
    ['HVAC', 'Commercial', 'EPA'],
  ),
];

export type JobsFallbackVariant = 'startup' | 'corporate' | 'tech' | 'modern' | 'freelance' | 'blue_collar';

const FALLBACK_BY_VARIANT: Record<JobsFallbackVariant, JobListing[]> = {
  startup: STARTUP_FALLBACK_JOBS,
  corporate: CORPORATE_FALLBACK_JOBS,
  tech: TECH_FALLBACK_JOBS,
  modern: MODERN_FALLBACK_JOBS,
  freelance: FREELANCE_FALLBACK_JOBS,
  blue_collar: BLUE_COLLAR_FALLBACK_JOBS,
};

export function getFallbackJobs(variant: JobsFallbackVariant): JobListing[] {
  return FALLBACK_BY_VARIANT[variant];
}

export function findFallbackJob(slug: string, variant: JobsFallbackVariant): JobListing | undefined {
  const exact = FALLBACK_BY_VARIANT[variant].find((job) => job.slug === slug);
  if (exact) return exact;

  if (variant === 'startup' || variant === 'tech') {
    const base = FALLBACK_BY_VARIANT[variant][0];
    return {
      ...base,
      id: 999,
      slug,
      title: slug.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase()),
      description:
        variant === 'tech'
          ? 'High-fidelity engineering opportunity. Solve mission-critical problems with modern tooling and strong autonomy.'
          : 'Hypergrowth startup looking for a mission-critical specialist to optimize dynamic corporate networks.',
      company: { name: variant === 'tech' ? 'Tech Startup' : 'Venture Corp', logo: null },
      taxonomy: {
        category: variant === 'tech' ? 'Engineering' : 'Technical Talent',
        tags: variant === 'tech' ? ['TypeScript', 'React', 'Remote'] : ['Startup', 'Next.js', 'Docker'],
      },
      location: { display: 'Remote', city: 'Remote', country: 'United States' },
    };
  }

  return undefined;
}

export function getRelatedFallbackJobs(slug: string, variant: JobsFallbackVariant): JobListing[] {
  return FALLBACK_BY_VARIANT[variant].filter((job) => job.slug !== slug).slice(0, 3);
}
